
tickets:tickets.c
	gcc $^ -o $@ -lpthread -g
pthread_detach:pthread_detach.c
	gcc $^ -o $@ -lpthread -g
pthread_join:pthread_join.c
	gcc $^ -o $@ -lpthread -g
thread_creat1:pthread_creat1.c
	gcc $^ -o $@ -lpthread -g
