all:test_wait
	

test_wait:test_wait.c
	gcc $^ -o $@

test:test.c
	gcc $^ -o $@
process:process.c
	gcc $^ -o $@
getenv:getenv.c
	gcc $^ -o $@
hello:hello.c
	gcc $^ -o $@
wait:wait.c
	gcc $^ -o $@
exit:exit.c
	gcc $^ -o $@
