Cond:Cond.c
	gcc $^ -o $@ -lpthread
tickets:tickets.c
	gcc $^ -o $@ -lpthread
pthread_detach:pthread_detach.c
	gcc $^ -o $@ -lpthread
pthread2:pthread2.c
	gcc $^ -o $@ -lpthread
Create_pthread:Create_pthread.c
	gcc $^ -o $@ -lpthread
